## Create table EventEmbedding

In [1]:
import pandas as pd
from makeEmbedding import makeJSONEmbedding

data = pd.read_csv("../dbService/dbScripts/fillScripts/fileStorage/dict.csv")
data["EXTERNAL_ID_event"] = (data['id_level1'].astype(str) +
                             data['id_level2'].astype(str) +
                             data['id_level3'].astype(str)).apply(int)

data["event_embedding_vector"] = data["d_level1"].apply(makeJSONEmbedding)

/Users/parutin/Developer/Projects/NoCountryForOldMen/venv/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Some weights of the model checkpoint at cointegrated/rubert-tiny were not used when initializing BertModel: ['cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.decoder.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.weight', 'cls.predictions.decoder.bias', 'cls.predictions.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing Ber

In [2]:
data[["EXTERNAL_ID_event", "event_embedding_vector"]].head()

EXTERNAL_ID_event                             event_embedding_vector
0         6496511042  [0.050233516842126846, -0.0693507045507431, -0...
1         6496511040  [0.03845700994133949, -0.06054828688502312, 0....
2         6496511041  [0.01180916465818882, -0.04440292716026306, -0...
3         6496511043  [0.06594925373792648, -0.007086414843797684, -...
4          649650323  [0.033936820924282074, -0.004341507330536842, ...

In [3]:
data[["EXTERNAL_ID_event", "event_embedding_vector"]].to_csv(
    "../dbService/dbScripts/fillScripts/fileStorage/EventEmbedding.csv", index=False
)

In [4]:
data = pd.read_csv("../dbService/dbScripts/fillScripts/fileStorage/EventEmbedding.csv")
data

EXTERNAL_ID_event                             event_embedding_vector
0           6496511042  [0.050233516842126846, -0.0693507045507431, -0...
1           6496511040  [0.03845700994133949, -0.06054828688502312, 0....
2           6496511041  [0.01180916465818882, -0.04440292716026306, -0...
3           6496511043  [0.06594925373792648, -0.007086414843797684, -...
4            649650323  [0.033936820924282074, -0.004341507330536842, ...
..                 ...                                                ...
894          589592656  [0.061259202659130096, -0.03955325111746788, 0...
895          589592140  [0.03513191267848015, -0.04580014944076538, 0....
896          589592129  [0.04869218170642853, -0.03678492084145546, 0....
897          589592481  [0.049559347331523895, -0.0419323705136776, -0...
898          589592154  [0.04191852733492851, -0.04061248525977135, 0....

[899 rows x 2 columns]

1, 2, 3


In [60]:
import pandas as pd
import numpy as np
import utils
l = 104586

In [61]:
a = utils.get_top_n_events_for_grand(l)
str(a)[1:-1]

'142, 184, 129, 132, 177, 130, 101, 422, 98, 511'

##

In [62]:
from dbService.dbConfiguration import get_request, put_request

In [63]:
b = get_request(query=f"""
    SELECT * FROM NoOldMen.StaticEvent WHERE SYS_ID_event IN ({str(a)[1:-1]})
""", execute_many=True)

In [64]:
for i in a:
    for j in b:
        if i == j[0]:
            print(j)

(142, 63113831421, 141, 'ОНЛАЙН Пеший лекторий_ОНЛАЙН Краеведение и онлайн-экскурсии', 'Занятия по изучению московской географии, истории, а также культурных и природных особенностей определенных мест столицы.', 'Образование', 'ОНЛАЙН Пеший лекторий', 'Для ума')
(184, 63113631369, 183, 'Пеший лекторий_Краеведение и пешие прогулки', 'Занятия по изучению московской географии, истории, а также культурных и природных особенностей определенных мест столицы.', 'Образование', 'Пеший лекторий', 'Для ума')
(129, 63113831789, 128, 'ОНЛАЙН Пеший лекторий_ОНЛАЙН Краеведение и онлайн-экскурсии по миру', 'Занятия по изучению географии, истории, а также культурных и природных особенностей определенных мест мира.', 'Образование', 'ОНЛАЙН Пеший лекторий', 'Для ума')
(132, 63113831782, 131, 'ОНЛАЙН Пеший лекторий_ОНЛАЙН Памятники культуры', 'Занятия в формате онлайн - экскурсий по ознакомлению с предметами и объектами исторического и культурного наследия.', 'Образование', 'ОНЛАЙН Пеший лекторий', 'Для у

In [65]:
utils.get_grand_meetings_info(l).value_counts("event_short_name")

event_short_name
ОНЛАЙН Пеший лекторий_ОНЛАЙН Краеведение и онлайн-экскурсии                       185
ОНЛАЙН История, искусство, краеведение_ОНЛАЙН История, культура России             66
ОНЛАЙН Образовательный практикум_ОНЛАЙН География. Путешествия вокруг света        48
ОНЛАЙН История, искусство, краеведение_ОНЛАЙН История искусства                    37
ОНЛАЙН Пеший лекторий_ОНЛАЙН Авторские курсы/маршруты                               8
ОНЛАЙН Пеший лекторий_ОНЛАЙН Краеведение и онлайн-экскурсии по Москве и России      7
ОНЛАЙН Пеший лекторий_ОНЛАЙН Религиоведение                                         7
ОНЛАЙН Пеший лекторий_ОНЛАЙН Наука                                                  6
ОНЛАЙН Образовательный практикум_ОНЛАЙН Эмоциональный интеллект                     4
ОНЛАЙН Иностранные языки_ОНЛАЙН Китайский язык                                      2
ОНЛАЙН Информационные технологии_ОНЛАЙН Осваиваем мобильные устройства              2
ОНЛАЙН История, искусство, краеведени

In [5]:
groups_for_test = pd.read_csv("../dbService/dbScripts/fillScripts/fileStorage/groups_for_test.csv", names=["groups"])
groups_for_test

groups
0     801362710
1     801353142
2     801362725
3     801362727
4     801362748
...         ...
1132  801372340
1133  801372354
1134  801372384
1135  801366477
1136  801366823

[1137 rows x 1 columns]

In [6]:
groups_for_test = str(list(groups_for_test.groups.values))[1:-1]

In [17]:
d = get_request(query=f"""
    SELECT a.*
    FROM NoOldMen.DynamicGroup a
    JOIN NoOldMen.StaticGroup b
      on a.SYS_ID_group = b.SYS_ID_group
    WHERE b.EXTERNAL_ID_group IN ({groups_for_test})
""", execute_many=True)

In [18]:
pd.DataFrame(d, columns=["sys_id_group", "shedule"]).to_csv("test.csv", index=False)

In [55]:
print((np.array([[1, 2, 3, 7], [4, 5, 6, 7], [7, 8, 9, 7]]).T * np.array([1, 0, 1])).T)

[[1 2 3 7]
 [0 0 0 0]
 [7 8 9 7]]


In [ ]:
import utils
from dbService.dbConfiguration import get_request, put_request

In [15]:
import utils
import pandas as pd
import numpy as np
from dbService.dbConfiguration import get_request, put_request

grand_sys_id = 100540

groups_for_test = pd.read_csv("../dbService/dbScripts/fillScripts/fileStorage/groups_for_test.csv", names=["groups"])

rec = []
local = []

for event in utils.get_top_n_events_for_grand(grand_sys_id, top_n=899):
    groups = get_request(query=f"""SELECT SYS_ID_group
    FROM NoOldMen.EventGroupMap WHERE SYS_ID_event={event}""", execute_many=True)
    for group in groups:
        group = group[0]
        ext_id = get_request(query=f"""SELECT EXTERNAL_ID_group
                    FROM NoOldMen.StaticGroup WHERE SYS_ID_group={group}""", execute_many=True)[0]
        if ext_id in groups_for_test.groups.values and len(get_request(
        query=f"""
                SELECT
                c.SYS_ID_event,
                b.SYS_ID_grand,
                e.event_short_name,
                c.group_address,
                c.group_online_status,
                a.group_schedule_raw
                 FROM NoOldMen.AttendanceGroup b
                 JOIN NoOldMen.DynamicGroup a
                   ON b.SYS_ID_group = a.SYS_ID_group
                 JOIN NoOldMen.StaticGroup c
                   ON b.SYS_ID_group = c.SYS_ID_group
                 JOIN NoOldMen.StaticEvent e
                   ON c.SYS_ID_event = e.SYS_ID_event
                WHERE b.SYS_ID_group = {group};
                """,
        execute_many=True
    )) != 0:
            rec.append(ext_id)
            local.append(group)
    if len(rec) >= 20:
        break

for group in local:
    print(group, end="\t")
    print(utils.get_group_info(group)['event_short_name'])

print(utils.get_grand_meetings_info(grand_sys_id).value_counts("event_short_name"))

91421	Художественно-прикладное творчество_Рукоделие и творчество
100125	Художественно-прикладное творчество_Рукоделие и творчество
100160	Художественно-прикладное творчество_Рукоделие и творчество
80259	Рисование_Основы академического рисунка и живописи
83260	Рисование_Основы академического рисунка и живописи
96239	ОНЛАЙН Художественно-прикладное творчество_ОНЛАЙН Рукоделие и творчество
94067	ОНЛАЙН Рисование_ОНЛАЙН Акварельная живопись
93779	ОНЛАЙН Красота и стиль_ОНЛАЙН Школа макияжа
93781	ОНЛАЙН Красота и стиль_ОНЛАЙН Школа макияжа
93825	ОНЛАЙН Красота и стиль_ОНЛАЙН Школа макияжа
94699	ОНЛАЙН Красота и стиль_ОНЛАЙН Школа макияжа
97085	ОНЛАЙН Красота и стиль_ОНЛАЙН Школа макияжа
93444	Художественно-прикладное творчество_Керамика (глина, тестопластика)
100126	Художественно-прикладное творчество_Керамика (глина, тестопластика)
100156	Художественно-прикладное творчество_Керамика (глина, тестопластика)
100162	Художественно-прикладное творчество_Керамика (глина, тестопластика)
92355	ОНЛА

In [11]:
get_request(
        query=f"""
                SELECT
                c.SYS_ID_event,
                b.SYS_ID_grand,
                e.event_short_name,
                c.group_address,
                c.group_online_status,
                a.group_schedule_raw
                 FROM NoOldMen.AttendanceGroup b
                 JOIN NoOldMen.DynamicGroup a
                   ON b.SYS_ID_group = a.SYS_ID_group
                 JOIN NoOldMen.StaticGroup c
                   ON b.SYS_ID_group = c.SYS_ID_group
                 JOIN NoOldMen.StaticEvent e
                   ON c.SYS_ID_event = e.SYS_ID_event
                WHERE b.SYS_ID_group = {99466};
                """,
        execute_many=True
    )

[]

In [17]:

[a[0] for a in get_request(
        query=f"""
                SELECT DISTINCT event_level_1 FROM NoOldMen.StaticEvent
                """,
        execute_many=True
    )]

['Игры',
 'Образование',
 'Пение',
 'Рисование',
 'Спецпроект / Интеллектуальный клуб',
 'Спецпроект / Московский театрал',
 'Спецпроект / Серебряный университет',
 'Спецпроект / Тренировки долголетия (спецпроект по медицинской реабилитации)',
 'Танцы',
 'Творчество',
 'Физическая активность']